### ISSUE TITLE
Demo terminates with uncaught exception

### ISSUE THREAD

**Issue by thesofakillers** [davidirobinson/image-retargeting#1]
Hi, I've been trying to run this demo on two different machines (one Mac OS, one Ubuntu 18.04) but it unfortunately terminates abruptly after ~ 15 mins with the following errors:

**Mac OS**
```bash
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: OpenCV(3.4.9) /tmp/opencv@3-20200105-46927-z3qqj3/opencv-3.4.9/modules/core/src/matrix_wrap.cpp:1658: error: (-215:Assertion failed) !fixedSize() in function 'release'

Abort trap: 6
```
**Ubuntu 18.04**
```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.9) /home/<myusername>/opencv-3.4.9/modules/core/src/matrix_wrap.cpp:1658: error: (-215:Assertion failed) !fixedSize() in function 'release'

Aborted (core dumped)
```

I should note that I had to edit CMakeLists.txt on both machines to include the following line
```text
set(CMAKE_CXX_STANDARD 14)
```
since I was getting a `no member named 'make_unique' in namespace 'std'` (see discussion [here](https://github.com/YuvalNirkin/find_face_landmarks/issues/6#issuecomment-300063313))

Do you have any clue why this is happening? Here is the script I am running:
`./src/seam_carving_demo -i ~/Desktop/landscape.jpg -w 0.5 -h 1 -v`

Finally, and perhaps this is a separate issue, but it seems like the verbose flag does not really do anything. 

Thank you for your work.

**Comment by davidirobinson** [comment]
Thanks for pointing that out. Could you send through the `landscape.jpg` image you were using? Did the demo fail with the images in the test folder? I'll try a build with OpenCV 3.4.9 and see if I run into the same issue.

I'll update the cpp version in the cmake folder.

I expect the verbose flag doesn't do anything because it's only used after the image has been resized (https://github.com/davidirobinson/image-retargeting/blob/master/src/demo.cc#L86). Perhaps I should rename it to something like `print-report`.

**Comment by thesofakillers** [comment]
Hey thanks for the quick response. I had the same thought as you regarding the image being problematic. Unfortunately I'm getting the same exact error with the test images in this repo. 
I'm currently trying to figure out what the problem is. So far I've narrowed it down to the `retarget` function in `seam_carving.cc` if that helps.

**Comment by thesofakillers** [comment]
[This specific line:](https://github.com/davidirobinson/image-retargeting/blob/695fe17fbd64de79ae5a54e5449c13c372ea7815/src/seam_carving.cc#L189)
https://github.com/davidirobinson/image-retargeting/blob/695fe17fbd64de79ae5a54e5449c13c372ea7815/src/seam_carving.cc#L189

Seems to be throwing the assertion error, for a very specific `row` (416) on the 40th iteration of the [column retargeting where we call `removeMinEnergySeam`](https://github.com/davidirobinson/image-retargeting/blob/695fe17fbd64de79ae5a54e5449c13c372ea7815/src/seam_carving.cc#L30-L37). 

Really strange, although idk what the fix would be. 
Please let me know if you have any clue, and thanks again for all the help and for open sourcing this.

**Comment by AbdullahJirjees** [comment]
Hi, Thanks a lot for the code, please could you explain to me how can  I run the code, I did git clone and I got vcpkg,
